# 日志配置
logging:
  level:
    top.lctr.jasypt.tools.console: debug
    org.springframework: warn

# Spring配置
spring:
#  profiles:
#    active: @env@-@os@
  # json配置
  jackson:
    mapper:
      # 接口反序列化参数时大小写不敏感
      accept-case-insensitive-properties: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/strings

#服务配置
service:
  #服务标识
  key: 00000000-0000-0000-0000-00000CONSOLE
  #服务名称
  name: jasypt工具控制台
  #版本号
  version: 1.0.0

jasypt:
  encryptor:
    password: ${JAVA_LCTR_TEST_JASYPT_PASSWORD}
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator